name: publish

# build the documentation whenever there are new commits on main
on:
    workflow_dispatch: 

# .github/workflows/ci-cd.yml
jobs:
    pypi-publish:
      name: Upload release to PyPI
      runs-on: ubuntu-latest
      environment:
        name: pypi
        url: https://pypi.org/p/pyrdfrules
      permissions:
        id-token: write
      steps:

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python 3.12
          uses: actions/setup-python@v3
          with:
              python-version: "3.12"
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
              pip install hatch
              if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Install dependencies
          run: |
            ./build.sh

        - name: Publish package distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1